Feature/layout tsx to sfc keep
Tencent/tdesign-vue-next-starter pull request #279
Opened 2022-09-01 07:54 UTC by zhangpaopao0609

### 🤔 这个 PR 的性质是？

- [x] 代码风格优化

### 🔗 相关 Issue

tsx部分代码改sfc: https://github.com/Tencent/tdesign-vue-next-starter/issues/275

### 💡 需求背景和解决方案

layouts tsx 代码重构为 vue 

### 📝 更新日志

- refactor: `layouts` `.tsx` 代码重构为 `.vue` 

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-09-03 15:15 UTC, timi137137 requested changes
请修改或回复以上问题，并解决文件冲突

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/LayoutContent.vue
> +  <t-layout :class="[`${prefix}-layout`]">
这个括号是必要的嘛？

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/LayoutContent.vue
> +        @remove="() => handleRemove(_route.path, idx)"
不要使用下划线开头做变量名称，并且变量名称需要带有含义，如`index`而不是`idx`

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +          <component :is="beRender(item).render" v-else-if="beRender(item).can" class="t-icon" />
这里的`<t-icon v-if="typeof item.icon === 'string' && item.icon" :name="item.icon" />`你不觉得很冗余吗，可以抽出来做一个方法

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
统一使用以下方法定义默认值
```ts
const props = defineProps({
  navData: {
    type: Array as PropType<MenuRoute[]>,
    default: () => [],
  },
});
```

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/SideNav.vue
> +);
问题同上

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/components/SideNav.vue
> +  return AssetLogoFull;
可以采用一行简写

2022-09-03 15:15 UTC, timi137137 commented on src/layouts/index.vue
> +import '@/style/layout.less';
把样式文件写在`style`代码块中，而不是在ts中

2022-09-03 15:40 UTC, uyarn commented on src/layouts/components/LayoutContent.vue
> +const tabRouters = tabsRouterStore.tabRouters.filter((route) => route.isAlive || route.isHome);
这里要computed一下 不然router只计算了一次 后面丢掉响应式了 多标签页功能都失效了。

2022-09-03 15:42 UTC, uyarn commented on src/layouts/components/LayoutContent.vue
> +const tabRouters = tabsRouterStore.tabRouters.filter((route) => route.isAlive || route.isHome);
<img width="1451" alt="image" src="https://user-images.githubusercontent.com/26377630/188278020-0b877ac1-b681-4e0d-aee0-0d8a551bc271.png">

2022-09-04 05:56 UTC, zhangpaopao0609 commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
正确的默认值定义就应该是这个

2022-09-04 05:57 UTC, zhangpaopao0609 commented on src/layouts/components/SideNav.vue
> +);
同上

2022-09-04 05:58 UTC, zhangpaopao0609 commented on src/layouts/components/LayoutContent.vue
> +  <t-layout :class="[`${prefix}-layout`]">
ok

2022-09-04 06:05 UTC, zhangpaopao0609 commented on src/layouts/components/LayoutContent.vue
> +        @remove="() => handleRemove(_route.path, idx)"
已修复

2022-09-04 06:08 UTC, zhangpaopao0609 commented on src/layouts/components/MenuContent.vue
> +          <component :is="beRender(item).render" v-else-if="beRender(item).can" class="t-icon" />
已修复

2022-09-04 06:09 UTC, zhangpaopao0609 commented on src/layouts/components/SideNav.vue
> +  return AssetLogoFull;
已修复

2022-09-04 06:10 UTC, zhangpaopao0609 commented on src/layouts/index.vue
> +import '@/style/layout.less';
已修复

2022-09-04 06:25 UTC, zhangpaopao0609 commented on src/layouts/components/MenuContent.vue
> +          <component :is="beRender(item).render" v-else-if="beRender(item).can" class="t-icon" />
已优化

2022-09-04 06:25 UTC, zhangpaopao0609 commented on src/layouts/components/LayoutContent.vue
> +        @remove="() => handleRemove(_route.path, idx)"
已优化

2022-09-04 06:26 UTC, zhangpaopao0609 commented on src/layouts/components/LayoutContent.vue
> +const tabRouters = tabsRouterStore.tabRouters.filter((route) => route.isAlive || route.isHome);
已修复

2022-09-04 07:12 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
你可以选择将全部代码的默认值改成这个，但是目前必须统一使用方式

2022-09-04 07:12 UTC, timi137137 commented on src/layouts/components/SideNav.vue
> +);
同上

2022-09-04 08:41 UTC, uyarn commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
@timi137137 这个issue shoot的范围是是针对这几个非sfc的文件做改造 PR已经达到改造范围了 如果我们要将全部代码改造是另一个PR来做这件事

2022-09-04 08:43 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
@uyarn 我我知道要另一个PR，所以我说了`但是目前必须统一使用方式`

2022-09-04 09:09 UTC, uyarn commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
@timi137137 理解 你的出发点也没问题 正好我看到另一个问题 顺便处理下 https://github.com/Tencent/tdesign-vue-next-starter/pull/279/commits/25e6ed069afc41a22b6af0b899556e877fb3cef7 有时候maintainer/collaborator 也需要处理一下仓库格式统一与正确与否的问题 anyways我们再提个issue来统一处理这个defineProps的格式问题吧

2022-09-04 09:09 UTC, timi137137 approved these changes

2022-09-04 09:10 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +const props = withDefaults(defineProps<{ navData: MenuRoute[] }>(), { navData: () => [] });
> @timi137137 理解 你的出发点也没问题 正好我看到另一个问题 顺便处理下 [25e6ed0](https://github.com/Tencent/tdesign-vue-next-starter/commit/25e6ed069afc41a22b6af0b899556e877fb3cef7) 有时候maintainer/collaborator 也需要处理一下仓库格式统一与正确与否的问题 anyways我们再提个issue来统一处理这个defineProps的格式问题吧

我觉得可以

2022-09-04 09:17 UTC, merged