fix: 解决当打开多个标签后 退出会报错的问题
Tencent/tdesign-vue-next-starter pull request #293
Opened 2022-09-05 07:30 UTC by PDieE

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

fix: activeRouteFullPath示例增加 suspense 用来解决当打开多个标签后 退出会报错的问题

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-09-05 09:43 UTC, timi137137 requested changes

2022-09-05 09:43 UTC, timi137137 commented on src/layouts/components/Content.vue
>  // 如果存在需解决/page/1=> /page/2 刷新数据问题 请修改代码 使用activeRouteFullPath 作为key
这里加一行
`// <suspense>标签属于实验性功能，请谨慎使用`

2022-09-06 03:29 UTC, PDieE commented on src/layouts/components/Content.vue
>  // 如果存在需解决/page/1=> /page/2 刷新数据问题 请修改代码 使用activeRouteFullPath 作为key
已加

2022-09-06 05:01 UTC, timi137137 approved these changes

2022-09-06 05:02 UTC, merged