fix: 菜单为链接时只点文字内容才跳转
Tencent/tdesign-vue-next-starter pull request #328
Opened 2022-10-01 07:26 UTC by dianjie

### 🤔 这个 PR 的性质是？

- [x] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x ] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2022-10-01 15:10 UTC, uyarn commented
changelog请补充完整

2022-10-01 15:35 UTC, timi137137 requested changes

2022-10-01 15:35 UTC, timi137137 commented on src/layouts/components/MenuContent.vue
> +const openHref = (url: string | undefined) => {
为什么不用?:呢，是有什么特别意义吗

2022-10-02 16:14 UTC, dianjie commented on src/layouts/components/MenuContent.vue
> +const openHref = (url: string | undefined) => {
> 为什么不用?:呢，是有什么特别意义吗

没有，本来用&&的，但触发eslint规则拦截了，就写成这了~

2022-10-21 00:48 UTC, closed without merging