feat: 多标签Tab页支持拖拽排序
Tencent/tdesign-vue-next-starter pull request #426
Opened 2023-02-20 01:51 UTC by liweijie0812

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- feat: 多标签Tab页支持拖拽排序

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-02-20 02:11 UTC, uyarn commented
没有其他问题 但是建议增加下对HomePage的判断 如果和HomePage换序就return不执行了 不然一些关闭左右的逻辑涉及HomePage的就也要跟着改动了
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/26377630/219993173-2feb8d9f-339e-401b-97e7-76d56c1eb673.png">

2023-02-20 02:57 UTC, liweijie0812 commented
> 没有其他问题 但是建议增加下对HomePage的判断 如果和HomePage换序( index 0 )就return不用执行了 不然一些关闭左右的逻辑涉及HomePage的就也要跟着改动了 <img alt="image" width="1466" src="https://user-images.githubusercontent.com/26377630/219993173-2feb8d9f-339e-401b-97e7-76d56c1eb673.png">

已调整，如果组件库tabs拖拽支持配置选项卡禁止拖拽更好

2023-02-20 05:41 UTC, uyarn commented
不对 .. 这个drag其实不是受控的 跟在dragend的回调里没有关系 ..

2023-02-20 14:34 UTC, timi137137 requested changes

2023-02-20 14:34 UTC, timi137137 commented on src/layouts/components/LayoutContent.vue
> +const handleDragend = ({ currentIndex, targetIndex }) => {
嗯....这边的分支在做迁移至严格模式，为了不增加工作量这边希望能够补全类型声明

2023-02-21 01:30 UTC, liweijie0812 commented
@uyarn 重新调整了右键关闭的逻辑，看看有没有问题

2023-02-21 03:17 UTC, timi137137 approved these changes
@uyarn LGTM，but需要先处理 #429 不然会出现大冲突

2023-02-21 03:36 UTC, uyarn approved these changes

2023-02-21 03:36 UTC, merged