fix: 优化修改主题色的逻辑
Tencent/tdesign-vue-next-starter pull request #428
Opened 2023-02-20 10:25 UTC by hzgotb

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

setting组件和setting store 有相同的逻辑代码，简化了一下。

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [x] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-02-20 14:35 UTC, timi137137 approved these changes

2023-02-20 14:36 UTC, timi137137 commented
@uyarn LGTM,but not test

2023-02-21 06:39 UTC, uyarn requested changes
有一点需要再修改
改动影响了明亮和暗黑模式的色阶逻辑 可以看出明亮和暗黑用的是一套色阶 
light mode
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/26377630/220266661-1f856a9d-5297-46c9-8d15-2b7007e25e17.png">
dark mode
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/26377630/220266185-2f3030cd-52ea-4017-8111-9e7282d99965.png">

可以对比下现在线上的

2023-02-22 08:14 UTC, hzgotb commented
ok。我看一下

2023-02-22 08:56 UTC, hzgotb commented
@uyarn 可以了。因为对颜色做了计算缓存，所以在切换其他模式的时候判断存在色阶所以不再计算。我改了一下判断的key

2023-02-23 17:07 UTC, uyarn approved these changes

2023-02-23 17:07 UTC, merged