fix: globEager deprecated
Tencent/tdesign-vue-next-starter pull request #439
Opened 2023-03-03 10:12 UTC by hmingv

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [ ] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [ ] 文档已补充或无须补充
- [ ] 代码演示已提供或无须提供
- [ ] TypeScript 定义已补充或无须补充
- [ ] Changelog 已提供或无须提供

2023-03-06 17:06 UTC, timi137137 requested changes

2023-03-06 17:06 UTC, timi137137 commented on .vscode/settings.json
> +  "nuxt.isNuxtApp": false
```suggestion
```
不要携带非通用参数，并不是每个人都需要这个参数的

2023-03-07 00:48 UTC, hmingv commented on .vscode/settings.json
> +  "nuxt.isNuxtApp": false
谢谢提醒。

2023-03-07 03:18 UTC, uyarn approved these changes

2023-03-07 03:20 UTC, timi137137 approved these changes

2023-03-07 03:21 UTC, merged

2025-01-13 06:17 UTC, Scutua approved these changes