feat: 国际化支持(#422)
Tencent/tdesign-vue-next-starter pull request #453
Opened 2023-03-26 07:56 UTC by jarmywang

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- feat: 国际化支持(#422)

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [x] 文档已补充或无须补充
- [x] 代码演示已提供或无须提供
- [x] TypeScript 定义已补充或无须补充
- [x] Changelog 已提供或无须提供

2023-03-27 07:19 UTC, timi137137 commented on src/layouts/components/Header.vue
> +          <t-tooltip placement="bottom" :content="$t('layout.code')">
vue3中不应该出现 **$** 符号开头的函数

2023-03-27 07:21 UTC, timi137137 commented on src/locales/lang/en.ts
> +  列表页: 'List Page',
不能出现中文命名

2023-03-27 07:22 UTC, timi137137 requested changes
根据以上问题进行修正，并且必须能过ci

2023-03-28 01:41 UTC, jarmywang commented
> 根据以上问题进行修正，并且必须能过ci

已修复

2023-03-28 04:55 UTC, closed without merging

2023-03-28 04:56 UTC, timi137137 commented
wait some times，因为分支名重叠了我分支炸了