feat: 增加配置侧边栏深色模式
Tencent/tdesign-vue-next-starter pull request #657
Opened 2023-12-30 17:52 UTC by qingmang

### 🤔 这个 PR 的性质是？

- [ ] 日常 bug 修复
- [x] 新特性提交
- [ ] 文档改进
- [ ] 演示代码改进
- [ ] 组件样式/交互改进
- [ ] CI/CD 改进
- [ ] 重构
- [ ] 代码风格优化
- [ ] 测试用例
- [ ] 分支合并
- [ ] 其他

### 🔗 相关 Issue

### 💡 需求背景和解决方案

### 📝 更新日志

- fix(组件名称): 处理问题或特性描述 ...

- [ ] 本条 PR 不需要纳入 Changelog

### ☑️ 请求合并前的自查清单

⚠️ 请自检并全部**勾选全部选项**。⚠️

- [X] 文档已补充或无须补充
- [X] 代码演示已提供或无须提供
- [X] TypeScript 定义已补充或无须补充
- [X] Changelog 已提供或无须提供

2023-12-30 23:13 UTC, timi137137 requested changes
前提：请看 #447

2023-12-30 23:13 UTC, timi137137 commented on src/layouts/components/LayoutSideNav.vue
> +    :theme="settingStore.displaySideMode"
为什么要新增多一个参数？意义在哪

2023-12-30 23:13 UTC, timi137137 commented on src/layouts/components/SideNav.vue
> +        color: white;
如果只是让图标变色的话，看起来目前已经可以实现了
![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/36812439/d422fd97-d52e-4ab5-b69e-7ca91716d69a)

2023-12-31 04:42 UTC, qingmang commented on src/layouts/components/LayoutSideNav.vue
> +    :theme="settingStore.displaySideMode"
我也不明白意义在哪,有的情况theme=light的时候,左侧栏可以单独设置为dark模式

![image](https://github.com/Tencent/tdesign-vue-next-starter/assets/67047984/b18eaf47-1f77-4e83-b5a8-0b1c3ad78285)

2023-12-31 04:44 UTC, timi137137 commented on src/layouts/components/LayoutSideNav.vue
> +    :theme="settingStore.displaySideMode"
@uyarn  评估一下有无需要，对于最简模板的情况下

2023-12-31 04:44 UTC, qingmang commented on src/layouts/components/SideNav.vue
> +        color: white;
如果全局是light模式的话 t-menu的theme为dark就要重写以下logo的色彩样式控制

2024-01-02 05:00 UTC, timi137137 commented
@qingmang 修正一下你的代码，测试不通过

2024-02-05 07:47 UTC, closed without merging